CREATE TABLE TIPO_CAMBIO (ID INT IDENTITY NOT NULL PRIMARY KEY, FECHA DATE NOT NULL, COMPRA MONEY, VENTA MONEY)
GO

INSERT INTO TIPO_CAMBIO VALUES ('20230510', 3.67, 3.678)

CREATE TABLE CABECERA_VENTA (ID INT IDENTITY NOT NULL PRIMARY KEY, FECHA DATE NOT NULL, SERIE VARCHAR(4) NOT NULL, NUMERO VARCHAR(10) NOT NULL, MONTO_SOLES MONEY NOT NULL, MONTO_DOLARES MONEY NOT NULL)
GO

INSERT INTO CABECERA_VENTA VALUES ('20230510', 'F001', '1597', 1000, 1000/3.678)

