-- Tablas Temporales
-- - TT Locales: I/O, lentas, ámbito sobre la conexión que creo la tabla
-- - TT Globales: I/O, lentas, ámbito a nivel de base de datos 
-- - CTE: en memoria, rápidas
-- - TT Variable: en memoria, rápidas

--Locales

CREATE TABLE #TEMP (ID INT PRIMARY KEY, FECHA DATE)

CREATE TABLE CALENDARIO (ID INT PRIMARY KEY, FECHA DATE)
INSERT INTO CALENDARIO VALUES (1, '20230101')
INSERT INTO CALENDARIO VALUES (2, '20230102')
INSERT INTO CALENDARIO VALUES (3, '20230103')

SELECT * FROM CALENDARIO

SELECT ID, FECHA INTO #TEMP1 FROM CALENDARIO WHERE 1 = 0 

SELECT * FROM #TEMP1

SELECT FECHA INTO #TEMP2 FROM CALENDARIO 

SELECT * FROM #TEMP2


SELECT *
FROM CALENDARIO C
	INNER JOIN #TEMP T ON C.ID = T.ID
	
--Global

CREATE TABLE ##TEMP (ID INT PRIMARY KEY, FECHA DATE)

SELECT ID, FECHA INTO ##TEMP1 FROM CALENDARIO WHERE 1 = 0 

SELECT ID, FECHA INTO ##TEMP2 FROM CALENDARIO 

ALTER PROC uP_Calendario_Consulta
	@FECHA_ANIO INT,
	@FECHA_MES SMALLINT
AS
BEGIN
	--V1
	--SELECT ID, FECHA
	--INTO #TEMP
	--FROM CALENDARIO
	--WHERE YEAR(FECHA) = @FECHA_ANIO
	--	AND MONTH(FECHA) = @FECHA_MES
	--SELECT * FROM #TEMP

	--V2
	SELECT ID, FECHA INTO #CALENDARIO FROM CALENDARIO WHERE 1 = 0

	INSERT INTO #CALENDARIO (ID, FECHA)
	SELECT ID, FECHA
	FROM CALENDARIO
	WHERE YEAR(FECHA) = @FECHA_ANIO
		AND MONTH(FECHA) = @FECHA_MES

	SELECT * FROM #CALENDARIO
	EXEC up_Testing
END

EXEC uP_Calendario_Consulta 2023, 1

SELECT * FROM #CALENDARIO

CREATE PROC up_Testing
AS
BEGIN
	SELECT * FROM #CALENDARIO
END

EXEC up_Testing


CREATE PROC uP_Calendario_Consulta_TTGlobal
	@FECHA_ANIO INT,
	@FECHA_MES SMALLINT
AS
BEGIN
	--V1
	--SELECT ID, FECHA
	--INTO #TEMP
	--FROM CALENDARIO
	--WHERE YEAR(FECHA) = @FECHA_ANIO
	--	AND MONTH(FECHA) = @FECHA_MES
	--SELECT * FROM #TEMP

	--V2
	SELECT ID, FECHA INTO ##CALENDARIO FROM CALENDARIO WHERE 1 = 0

	INSERT INTO ##CALENDARIO (ID, FECHA)
	SELECT ID, FECHA
	FROM CALENDARIO
	WHERE YEAR(FECHA) = @FECHA_ANIO
		AND MONTH(FECHA) = @FECHA_MES

	SELECT * FROM ##CALENDARIO
	--EXEC up_Testing
END
GO

EXEC uP_Calendario_Consulta_TTGlobal 2023, 1

CREATE PROC up_Testing_TTGlobal
AS
BEGIN
	SELECT * FROM ##CALENDARIO
END


up_Testing_TTGlobal

drop table ##CALENDARIO

-- cte
WITH
CTE
AS
(
	SELECT ID, FECHA FROM CALENDARIO
),
CTE_MAX_MIN
AS
(
	SELECT MAX(FECHA) AS FECHA_MAXIMA, MIN(FECHA) AS FECHA_MINIMA
	FROM CTE
)
SELECT * 
INTO #CTE
FROM CTE C
WHERE FECHA = (SELECT FECHA_MINIMA FROM CTE_MAX_MIN)

SELECT * FROM #CTE

;WITH
CTE
AS
(
	SELECT CONVERT(DATE, '20230101') AS FECHA
	UNION ALL
	SELECT DATEADD(D, 1, FECHA)
	FROM CTE
	WHERE FECHA < '20230131'
)
SELECT * FROM CTE



;WITH
CTE
AS
(
	SELECT CONVERT(DATE, '20230201') AS FECHA
	UNION ALL
	SELECT DATEADD(D, 1, FECHA)
	FROM CTE
	WHERE FECHA < '20230228'
)
INSERT INTO CALENDARIO (ID, FECHA)
SELECT DAY(FECHA) * 10, FECHA FROM CTE


