CREATE TABLE [dbo].[PROVEEDOR](
	[ID] [int] NOT NULL,
	[RAZON_SOCIAL] [varchar](1000) NOT NULL,
 CONSTRAINT [PK_PROVEEDOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (1, N'PROVEEDOR 1')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (2, N'PROVEEDOR 2')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (3, N'PROVEEDOR 3')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (4, N'PROVEEDOR 4')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (5, N'PROVEEDOR 5')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (6, N'PROVEEDOR 6')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (7, N'PROVEEDOR 7')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (8, N'PROVEEDOR 8')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (9, N'PROVEEDOR 9')
INSERT [dbo].[PROVEEDOR] ([ID], [RAZON_SOCIAL]) VALUES (10, N'PROVEEDOR 10')
GO
