-- CONEXION B
/*
SET TRANSACTION ISOLATION LEVEL
[READ COMMITTED], [READ UNCOMMITTED], [REPEATABLE READ], [SERIALIZABLE], [SNAPSHOT], [READ COMMITTED SNAPSHOT]
*/

--TEST 1 - BLOQUEOS


--TEST 2 - ISOLATION LEVEL


--TEST 3 - LECTURAS SUCIAS
SET TRANSACTION ISOLATION LEVEL 


BEGIN TRANSACTION B

ROLLBACK TRANSACTION B

-- TEST 4 - LECTURA NO REPETIBLE
SET TRANSACTION ISOLATION LEVEL 

BEGIN TRANSACTION B

ROLLBACK TRANSACTION B

-- TEST 5 - LECTURA FANTASMA
SET TRANSACTION ISOLATION LEVEL 

BEGIN TRANSACTION B

ROLLBACK TRANSACTION B

-- TEST - ABRAZO MORTAL
SET TRANSACTION ISOLATION LEVEL 

BEGIN TRANSACTION B

ROLLBACK TRANSACTION B


/*
SELECT * FROM SYSOBJECTS WHERE ID IN (1131151075, 949578421, 1429580131)
*/