USE LAB_TBD
GO

CREATE TABLE CALENDAR (CALE_ID INT NOT NULL, CALE_FECHA DATE NOT NULL, CALE_ANIO INT NOT NULL, CALE_MES TINYINT NOT NULL, CALE_DIA TINYINT NOT NULL, CALE_MES_DESC VARCHAR(20) NULL)
GO

DECLARE @FECHA DATE = '20220101'

;WITH
CTE
AS
(
	SELECT 1 AS CALE_ID, @FECHA AS CALE_FECHA
	UNION ALL
	SELECT CALE_ID + 1, DATEADD(D, 1, CALE_FECHA) AS CALE_FECHA
	FROM CTE
	WHERE CALE_FECHA < '20221127'
)
INSERT INTO CALENDAR
SELECT CALE_ID, CALE_FECHA, YEAR(CALE_FECHA) AS CALE_ANIO, MONTH(CALE_FECHA) AS CALE_MES, DAY(CALE_FECHA) AS CALE_DIA
FROM CTE
OPTION (MAXRECURSION 0)


--CONSTRAINT
-- PRIMARY KEY
-- UNIQUE 
-- FOREIGN KEY 
-- CHECK
-- DEFAULT

SELECT * FROM CALENDAR

-- PRIMARY KEY


-- UNIQUE 


-- FOREIGN KEY


-- CHECK

-- DEFAULT

